name: "whatsapp-clone"

services:
  postgres:
    container_name: postgres-whatsapp
    image: 'postgres:latest'
    volumes:
      - postgresvolume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
    ports:
      - "5432:5432"
  keycloak:
    container_name: keycloak-whatsapp
    image: quay.io/keycloak/keycloak:24.0.2
    command: 'start-dev'
    volumes:
      - keycloak:/opt/keycloak/data/import
    environment:
      - KC_DB=dev-file
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_FEATURES=scripts
      - KC_HTTP_PORT=9080
      - KC_HTTPS_PORT=9443
    ports:
      - '9080:9080'
      - '9443:9443'

networks:
  yvolabs:
    driver: bridge

volumes:
  postgresvolume:
  keycloak: