name: "whatsapp-clone"

services:
  postgres:
    container_name: postgres-whatsapp
    image: 'postgres:latest'
    volumes:
      - postgresvolume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
    ports:
      - "5432:5432"

networks:
  yvolabs:
    driver: bridge

volumes:
  postgresvolume: